repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        exclude: docs/mkdocs.yml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.14
  hooks:
    # Run the linter.
    - id: ruff
      exclude: docker
      types_or: [ python, pyi ]
      args: [ --select, I, --fix ]
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.19.1'  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      additional_dependencies: [
          "ray",
           "pydantic>=2.0.0",  # Installe pydantic dans l'environnement de mypy
           "types-requests"   # (Optionnel) exemple pour d'autres stubs
      ]
      args: [ --ignore-missing-imports, --install-types, --non-interactive, --strict, --allow-subclassing-any ]
