[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mol_gen_docking"
version = "2025.8.4"
dependencies = [
    "torch>=2.6.0",
    "ray",
    "selfies",
    "fastapi",
    "PyTDC",
    "coverage",
    "pytest",
    "coverage-badge",
    "loguru",
    "omegaconf",
    "hydra-core",
    "peft",
    "transformers",
    "tokenizers",
    "datasets",
]

requires-python = ">=3.10"
description = ""

[tool.mypy]
disable_error_code = ["type-arg"]

[project.entry-points."vllm.general_plugins"]
register_dummy_model = "mol_gen_docking.models.vllm_model.register:register"
