[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mol_gen_docking"
version = "2025.8.4"
dependencies = [
    "torch==2.6.0",
    "torchvision",
    "torchaudio",
    "datasets",
    "PyTDC",
    "coverage",
    "pytest",
    "coverage-badge",
    "loguru",
    "omegaconf",
    "hydra-core",
]

requires-python = ">=3.10"
description = ""

[project.optional-dependencies]
orz = [
    "vllm",
    "tensorboard",
    "deepspeed",
    "flash-attn",
    "peft",
]
