[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mol_gen_docking"
version = "2025.8.4"
dependencies = [
    "torch==2.6.0",
    "torchvision",
    "torchaudio",
    "PyTDC",
    "vllm",
    "loguru",
    "omegaconf",
    "hydra-core",
    "tensorboard",
    "deepspeed",
    "flash-attn",
    "peft"
]
requires-python = ">=3.10"
description = ""
